config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :cards
  resources :users

  post :signin, to: "sessions#create"
  get :signin, to: "sessions#new"
  post :signout, to: "sessions#destroy"

  get '/check', to: 'home#check'

  root to: 'home#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :original_text, :translated_text, presence: true
  validate :texts_are_not_the_same?

  before_create :default_review_algorithm

  REVIEW_TIME_GAP = 3

  def self.random
    due_today.order("RANDOM()").first
  end

  def self.due_today
    where("review_date <= ?", DateTime.now.to_date)
  end

  def update_review_date
    new_review_date = review_date + REVIEW_TIME_GAP
    update(review_date: new_review_date)
  end

  def right_translation?(answer)
    sanitized_answer = answer.gsub(/[\s,\W+]/, '')
    sanitized_orig_text = original_text.gsub(/[\s,\W+]/, '')
    sanitized_answer.casecmp?(sanitized_orig_text)
  end

  protected

  def default_review_algorithm
    self.review_date = DateTime.now + REVIEW_TIME_GAP if review_date.nil?
  end

  def texts_are_not_the_same?
    errors.add(:translated_text, "Please Ensure that the texts are not the same!") if original_text.casecmp?(translated_text)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cards
  authenticates_with_sorcery!

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception

  private

  def not_authenticated
    redirect_to signin_path, alert: "Please sign in or register first"
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = current_user.cards
  end

  def new
    @card = Card.new
  end

  def show
    @card = Card.find(params[:id])
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      flash[:notice] = "Card successfully created!"
      redirect_to @card
    else
      flash[:error] = "Please complete the fields or ensure that you're not using the same text."
      render 'new'
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      flash[:notice] = "Card successfully updated!"
      redirect_to @card
    else
      flash[:error] = "Please complete the fields or ensure that you're not using the same text."
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])

    @card.destroy
    flash[:notice] = "Card successfully deleted!"
    redirect_to cards_path
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @card = current_user.cards.random
  end

  def check
    @card = Card.find(params[:card][:hidden_id])
    if @card.right_translation?(params[:card][:original_text])
      flash[:notice] = "Right!"
      @card.update_review_date
    else
      flash[:error] = "Wrong! (Or ensure your spelling is correct)"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if login(params[:signin][:email], params[:signin][:password])
      flash[:notice] = 'Login successful'
      redirect_to root_path
    else
      flash[:error] = 'Login failed'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash[:noice] = "User successfully created"
      redirect_to root_path
    else
      flash[:error] = "Please enter a valid email or ensure your PW has at least 8 characters"
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "User successfully updated!"
      redirect_to @user
    else
      flash[:error] = "Please review the errors below."
      render 'edit'
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |c| %>
  <%= c.input :original_text, label: "front of card" %>
  <%= c.input :translated_text, label: "back of card" %>
  <%= c.input :user_id, as: "hidden", input_html: {value: current_user.id} %>
  <%= c.button :submit %>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit a Card</h1>

<%= link_to 'Back to All cards', cards_path %><br>
<%= link_to "Delete Card", card_path(@card), method: :delete, data: {confirm: "Are you sure?"} %><br>

<%= render 'form' %>

app/views/cards/index.html.erb
<h1>Flashcard Collection</h1>

<%= link_to 'Create a New Card', new_card_path %><br>

<% @cards.each do |card| %>
  <h2> Card #<%=card.id%> </h2><br>
  Original Text: <%= card.original_text %><br>
  Translated Text: <%= card.translated_text %><br>
  Review Date: <%= card.review_date.strftime("%d/%m/%Y") %><br>
  <%= link_to "Edit Card", edit_card_path(card) %><br>
  <%= link_to "Delete Card", card_path(card), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/cards/new.html.erb
<h1>Create a Card</h1>

<%= link_to 'Back to All cards', cards_path %><br>

<%= render 'form' %>

app/views/cards/show.html.erb
<h1>Card #<%= @card.id %></h1>

<%= link_to 'Back to All cards', cards_path %><br>
<%= link_to 'Edit Card', edit_card_path(@card) %><br>
<%= link_to "Delete Card", card_path(@card), method: :delete, data: {confirm: "Are you sure?"} %><br>

<p>Original Text: <%= @card.original_text %> </p>
<p>Translated Text: <%= @card.translated_text %> </p>
<p>Next Review Date: <%= @card.review_date %> </p>

app/views/home/_quiz.html.erb
<%= simple_form_for @card, url: { action: "check" }, method: "get" do |c| %>
  <%= c.input :original_text, label: "Enter your Answer Here", input_html: { value: ''} %>
  <%= c.input :hidden_id, as: "hidden", input_html: {value: @card.id} %>
  <%= c.input :user_id, as: "hidden", input_html: {value: current_user.id} %>
  <%= c.button :submit, value: "Check" %>
<% end %>

app/views/home/check.html.erb
<section>
  <p style="font-size: 22px;">
    The answer is "<%= @card.original_text %>"
  </p>
</section>

<section>
  <%= link_to 'Next Due Card', root_path, :class => "btn btn-default" %>
</section>

app/views/home/welcome.html.erb
<section>
  <p style="font-size: 22px;">
  <% if @card %>
     Translated Text: <%= @card.translated_text %> <br>
     <%= render 'quiz' %>
  <% else %>
     No more due cards!
  <% end %>
  </p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section id="container">
    <header class="clearfix">
      <h1>Flashcard Manager (DE/EN)</h1>
      <ul class="navigation-links">
        <li><%= link_to 'All Cards', cards_path %></li>
        <li><%= link_to 'Review', root_path %></li>
        <li><%= link_to 'Add Card', new_card_path %></li>
        <% if current_user %>
          <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
          <li><%= link_to "Sign out", :signout, method: "post" %></li>
        <% else %>
          <li><%= link_to "Register", new_user_path %></li>
          <li><%= link_to "Sign in", :signin %></li>
        <% end %>
      </ul>
    </header>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
  </section>
  </body>
</html>

app/views/users/_form.html.erb
<h1>Register</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :email, label: "Email" %>
  <%= f.input :password, label: "Password" %>
  <%= f.input :password_confirmation, label: "Password Confirmation" %>
  <%= f.button :submit, value: "Submit" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= link_to 'Back to Review', root_path %><br>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<%= link_to 'Back to Review', root_path %><br>

<p>Email: <%= @user.email %> </p>
<p>Number of cards in total: <%= @user.cards.count %> </p>